"""empty message

Revision ID: 29e0a3973feb
Revises: ee161b32bad0
Create Date: 2018-04-08 15:47:58.988559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29e0a3973feb'
down_revision = 'ee161b32bad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_hash')
    # ### end Alembic commands ###
