"""04041534userinfo

Revision ID: 83faec6f2096
Revises: 59279d138bb5
Create Date: 2018-04-04 15:36:17.068772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83faec6f2096'
down_revision = '59279d138bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.TEXT(), nullable=True))
    op.add_column('users', sa.Column('last_time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('register_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_time')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_time')
    op.drop_column('users', 'about_me')
    # ### end Alembic commands ###
