"""empty message

Revision ID: 8ee252d8063d
Revises: 83faec6f2096
Create Date: 2018-04-05 17:28:45.024440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee252d8063d'
down_revision = '83faec6f2096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('new_email', sa.VARCHAR(length=20), nullable=True, server_default="nomail"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'new_email')
    # ### end Alembic commands ###
