"""empty message

Revision ID: b410d70360ce
Revises: d51911d3e5e4
Create Date: 2018-04-04 13:24:41.706208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b410d70360ce'
down_revision = 'd51911d3e5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'age')
    # ### end Alembic commands ###
