"""empty message

Revision ID: cc6add91d2d8
Revises: 04e0ad8a7777
Create Date: 2018-04-04 13:30:49.902634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc6add91d2d8'
down_revision = '04e0ad8a7777'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('age', sa.Integer()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'age')
    # ### end Alembic commands ###
